### ISSUE TITLE
which file caused trigger

### ISSUE THREAD

**Issue by bigmonkeyboy** [3rd-Eden/fs.notify#3]
If I watch several directories at once -  and a file in one changes - I can't see the full path of the file to know which directory it was in.... can the event have the path (or even FSwatcher) added to it ?  eg make line 236

  this.emit('change', filename, event, FSWatcher.path);

That should be non-breaking for existing users

**Comment by 3rd-Eden** [comment]
I'll accept a pull request + test for this, if you are up to it.

**Comment by bigmonkeyboy** [comment]
Not really. My test capabilities suck. I'd only add more bugs than remove. The one line to change if possible is above.
thanks

**Comment by 3rd-Eden** [comment]
Fixed in master.
